eslint/js

espree.js
lib/features.js
lib/messages.js
tests/fixtures/ecma-features-mix/objectLiteralDuplicateProperties-and-objectLiteralComputedProperties/proto-computed-property.config.js
tests/fixtures/ecma-features-mix/objectLiteralDuplicateProperties-and-objectLiteralComputedProperties/proto-computed-property.result.js
tests/fixtures/ecma-features-mix/objectLiteralDuplicateProperties-and-objectLiteralComputedProperties/proto-computed-property.src.js
tests/fixtures/ecma-features/objectLiteralDuplicateProperties/proto-property.result.js
tests/fixtures/ecma-features/objectLiteralDuplicateProperties/proto-property.src.js
tests/fixtures/ecma-features/objectLiteralDuplicateProperties/proto-string-property.result.js
tests/fixtures/ecma-features/objectLiteralDuplicateProperties/proto-string-property.src.js
tests/fixtures/ecma-features/objectLiteralDuplicateProperties/strict-duplicate-properties.result.js
tests/fixtures/ecma-features/objectLiteralDuplicateProperties/strict-duplicate-properties.src.js
tests/fixtures/ecma-features/objectLiteralDuplicateProperties/strict-duplicate-string-properties.result.js
tests/fixtures/ecma-features/objectLiteralDuplicateProperties/strict-duplicate-string-properties.src.js

- Adds support for duplicate object properties in ES 6 with the `duplicateObjectLiteralProperties` feature. 
- Continues to forbid duplicate object literals in strict mode otherwise
- Special rules for the `__proto__` property
This feature doesn't exist in esprima-fb yet, so we couldn't use it to help generate tests. Instead all tests were created by this branch and then verified by me. It looks good to me, but a few more pairs of eyes couldn't hurt.

New: Add support for duplicate object literal properties

---

README.md
espree.js
lib/features.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-defaultParams/default-params.config.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-defaultParams/default-params.result.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-defaultParams/default-params.src.js
tests/fixtures/ecma-features/defaultParams/declaration.result.js
tests/fixtures/ecma-features/defaultParams/declaration.src.js
tests/fixtures/ecma-features/defaultParams/expression.result.js
tests/fixtures/ecma-features/defaultParams/expression.src.js
tests/fixtures/ecma-features/defaultParams/method.result.js
tests/fixtures/ecma-features/defaultParams/method.src.js
tests/fixtures/ecma-features/defaultParams/not-all-params.result.js
tests/fixtures/ecma-features/defaultParams/not-all-params.src.js

Basically a simple port of ariya/esprima@0384add.
Destructuring isn't a feature yet, so we're not testing that inside of default params, though it's pretty important as well. Let me know if I missed anything.

New: Add support for default parameters (refs #10)

---

espree.js
tests/fixtures/ecma-features-mix/forOf-operator/for-of-declaring-inline.config.js
tests/fixtures/ecma-features-mix/forOf-operator/for-of-declaring-inline.result.js
tests/fixtures/ecma-features-mix/forOf-operator/for-of-declaring-inline.src.js
tests/fixtures/ecma-features-mix/forOf-operator/for-of-declaring.config.js
tests/fixtures/ecma-features-mix/forOf-operator/for-of-declaring.result.js
tests/fixtures/ecma-features-mix/forOf-operator/for-of-declaring.src.js

Enable forOf
```
{ forOf: true }
```
Espree will error with "undefined" 
```
for (var k in console) {
doSomething();
}
```
See test files in PR for examples.

When ecmaFeatures.forOf is true, check for operator is "undefined" when match keyword is "in" #39

---

espree.js
tests/fixtures/tokenize/template-string-embedded-result.tokens.js
tests/fixtures/tokenize/template-string-expressions-result.tokens.js
tests/fixtures/tokenize/template-string-simple-result.tokens.js
tests/lib/tokenize.js

Template strings really mess with tokenization because the tokens actually are different depending on the context before a `}` is encountered. Yuck. But the nice thing now is that this code:
```
`Hi ${foo} you.`;
```
Will produce:
1. `` "`Hi ${" `` (Template)
2. `"foo"` (identifier)
3. `` "} you.`" `` (Template)

Fix: Tokenization for template strings (fixes #44)

---

tools/create-test.js

When you mess up the pattern it wasn't showing the correct error. It used to show:
```
/Users/jamuferguson/dev/espree/tools/create-test.js:72
if (sections.length !== code.length) {
^
TypeError: Cannot read property 'length' of null
at Object.<anonymous> (/Users/jamuferguson/dev/espree/tools/create-test.js:72:13)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:929:3
```

Fix: create-test tool not complaining properly

---

espree.js
tests/fixtures/ast/Object-Initializer.json
tests/fixtures/ast/Tolerant-parse.json
tests/fixtures/ecma-features-mix/destructuring-and-defaultParams/param-object-short.result.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-defaultParams/default-params.result.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-destructuring/array-destructuring.result.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-generators/generator-object-literal-method.result.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-objectLiteralComputedProperties/computed-method-property.result.js
tests/fixtures/ecma-features-mix/restParams-and-destructuring/shortHand-destructuring-array.result.js
tests/fixtures/ecma-features-mix/restParams-and-destructuring/shortHand-multi-destructuring.result.js
tests/fixtures/ecma-features/objectLiteralComputedProperties/computed-getter-and-setter.result.js
tests/fixtures/ecma-features/objectLiteralShorthandMethods/method-property.result.js
tests/fixtures/ecma-features/objectLiteralShorthandMethods/simple-method-named-get.result.js
tests/fixtures/ecma-features/objectLiteralShorthandMethods/simple-method-named-set.result.js
tests/fixtures/ecma-features/objectLiteralShorthandMethods/simple-method-with-argument.result.js
tests/fixtures/ecma-features/objectLiteralShorthandMethods/simple-method-with-string-name.result.js
tests/fixtures/ecma-features/objectLiteralShorthandMethods/simple-method.result.js
tests/fixtures/ecma-features/objectLiteralShorthandMethods/string-name-method-property.result.js

This is jquery/esprima#1036 ported to Espree.
Previously, the range and loc for get, set, and shorthand methods inside object literal properties included only the method body, meaning a method's parameters were outside the range of their parent `FunctionExpression` node. This was happening because the marker for the `FunctionExpression` node wasn't being created until `parsePropertyFunction` was called, by which point the mothod's parameters had already been parsed. This PR solves the issue by creating the marker for the start of the `FunctionExpression` node as soon as it determines that the property is a get, set, or shorthand method, then passing the marker into `parsePropertyFunction`.
Though #36 only describes the specific case of generator shorthand methods, the same bug is present …

Fix: Extend property method range and loc to include params (fixes #36)

---

espree.js
tests/fixtures/ecma-features/modules/error-function.result.js
tests/fixtures/ecma-features/modules/error-function.src.js
tests/fixtures/modules/import/error-function.result.js
tests/fixtures/modules/import/error-function.src.js

- 1 test for `import`
- 1 test for `export`
let me know if you think we ought to go into each of various permutations.
fat arrows might be a good idea as well.

Test: disallow import/export in function body

---

espree.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default-anonymous-extends.config.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default-anonymous-extends.result.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default-anonymous-extends.src.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default-anonymous.config.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default-anonymous.result.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default-anonymous.src.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default-extends.config.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default-extends.result.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default-extends.src.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default.config.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default.result.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-default.src.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-extends.config.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-extends.result.js
tests/fixtures/ecma-features-mix/modules-and-classes/class-extends.src.js
tests/fixtures/ecma-features-mix/modules-and-classes/class.config.js
tests/fixtures/ecma-features-mix/modules-and-classes/class.result.js
tests/fixtures/ecma-features-mix/modules-and-classes/class.src.js

Added tests for the following:
Fixed the following:
Need to check the following:
The ASTs are tricky and need to be verified as accurate, because they were generated by espree.

Test: missing tests for modules & classes (refs #72)

---

README.md

The Esprima-FB project recently renamed all references of `XJS` to
`JSX`, so this should no longer be listed as an incompatibility.
- https://github.com/facebook/esprima/issues/83
- https://github.com/facebook/esprima/pull/85

Remove XJS note from Esprima-FB incompatibilities

---

espree.js
tests/fixtures/ecma-features-mix/classes-and-generators/classes-and-generators.config.js
tests/fixtures/ecma-features-mix/classes-and-generators/classes-and-generators.result.js
tests/fixtures/ecma-features-mix/classes-and-generators/classes-and-generators.src.js
tests/fixtures/ecma-features-mix/classes-and-generators/error-generator.config.js
tests/fixtures/ecma-features-mix/classes-and-generators/error-generator.result.js
tests/fixtures/ecma-features-mix/classes-and-generators/error-generator.src.js
tests/fixtures/ecma-features-mix/classes-and-generators/error-no-class.config.js
tests/fixtures/ecma-features-mix/classes-and-generators/error-no-class.result.js
tests/fixtures/ecma-features-mix/classes-and-generators/error-no-class.src.js
tests/fixtures/ecma-features-mix/classes-and-generators/error-static-no-generators.config.js
tests/fixtures/ecma-features-mix/classes-and-generators/error-static-no-generators.result.js
tests/fixtures/ecma-features-mix/classes-and-generators/error-static-no-generators.src.js
tests/fixtures/ecma-features-mix/classes-and-generators/static-generators.config.js
tests/fixtures/ecma-features-mix/classes-and-generators/static-generators.result.js
tests/fixtures/ecma-features-mix/classes-and-generators/static-generators.src.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-generators/error-no-shorthand.config.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-generators/error-no-shorthand.result.js
tests/fixtures/ecma-features-mix/objectLiteralShorthandMethods-and-generators/error-no-shorthand.src.js

Fix: generator methods in classes (fixes #85)

---

espree.js
tests/fixtures/ecma-features/classes/invalid-class-setter-declaration.result.js
tests/fixtures/ecma-features/classes/invalid-class-setter-declaration.src.js

I had some troubles getting a test to pass without resorting to the double definition of `message` and `description`, if you could provide some guidance I'd fix it.

Fix: bad error in parsing invalid class setter (fixes #98)

---

espree.js
tests/fixtures/ast/Invalid-syntax.json

This fix follows a pattern used elsewhere in the codebase

Fix: Incomplete Switch Statement Hangs (Fixes #146)

---

README.md

Related to https://github.com/eslint/espree/issues/153

Docs: added missing `ecmaFeatures.superInFunctions` option from doc

---

Makefile.js

When I ran `npm run browserify` I got this error. The fix seemed to be to copy `package.json` into `tmp`. Have you seen this before?
```
➜  espree git:(cleanup-makefile) ✗ npm run browserify
> espree@2.0.4 browserify /Users/jlaster/src/_os/_js/espree
> node Makefile.js browserify
Error: Cannot find module './package.json' from '/Users/jlaster/src/_os/_js/espree/tmp'
at /Users/jlaster/src/_os/_js/espree/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
at load (/Users/jlaster/src/_os/_js/espree/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
at onex (/Users/jlaster/src/_os/_js/espree/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
at …
```

Fix npm browserify

---

README.md
espree.js
lib/features.js
tests/fixtures/ecma-features/impliedStrict/global-strict-violation.result.js
tests/fixtures/ecma-features/impliedStrict/global-strict-violation.src.js
tests/fixtures/ecma-features/impliedStrict/inner-strict-violation.result.js
tests/fixtures/ecma-features/impliedStrict/inner-strict-violation.src.js
tests/lib/ecma-features.js

- New feature `ecmaFeatures.impliedStrict`.
- README.
- Two tests.
- Modified tests/lib/ecma-features.js:
- `ecmaFeatures[feature] = true` throws for `impliedStrict`.

New: ecmaFeatures.impliedStrict (fixes: #227)

---

package.json
tests/fixtures/ecma-version/6/modules/import-named-as-specifier-keyword.result.js
tests/fixtures/ecma-version/6/modules/import-named-as-specifier-keyword.src.js
tests/fixtures/ecma-version/6/modules/invalid-import-named-as-keyword.result.js
tests/fixtures/ecma-version/6/modules/invalid-import-named-as-keyword.src.js
tests/fixtures/ecma-version/6/modules/invalid-import-named-keyword.result.js
tests/fixtures/ecma-version/6/modules/invalid-import-named-keyword.src.js

fixes #225.
I fixed this in https://github.com/ternjs/acorn/commit/327d631aa38c75c1d8a97bcb6ba3aca4a148464f
So I just add tests for this.
The test of `ecma-version/6/modules/invalid-import-named-keyword` had been failing with `acorn@2.6.4`.
Then the test gets passing with `acorn@2.7.0`.

Fix: tests for importing keywords (fixes #225)

---

espree.js
tests/lib/acorn-after-espree.js

fixes #250
This PR contains indent changes, so `?w=1` would help to see actual changes.

Fix: use the plugins feature of acorn (fixes #250)

---

lib/comment-attachment.js
tests/fixtures/attach-comments/comment-within-previous-node.result.js
tests/fixtures/attach-comments/comment-within-previous-node.src.js

Looks like the `mootools` test is failing. Not sure if this means my change is bad or the expected output from the test is incorrect now that this change has been made. Are these generated with a command somewhere?
I ran this version of my change against the current master branch to test for speed and was surprised to find no conclusive evidence of this slowing things down (most likely because my change only runs on comments and only when the node type is `Program`)...Some tests were a bit slower, and others were a bit faster. So doesn't seem like a huge impact on performance :+1:

Fix: leading comments added from previous node (fixes #256)

---

lib/comment-attachment.js
tests/fixtures/attach-comments/comment-within-previous-node2.result.js
tests/fixtures/attach-comments/comment-within-previous-node2.src.js

While adding tests to the main ESLint repo to account for the changes I made in https://github.com/eslint/espree/pull/257 I realized that some of my initial assumptions were wrong:
- That the `body` prop is always an array (in reality it can be an array or an object)
- I didn't check the `body` props recursively (I had incorrectly thought the `Program` node's `body` contained all the nodes, which, in retrospect, is pretty silly)
This means that my current merged fix does not account for this case, as the comment to remove is nested a few levels deep, with the `body` props being a mixture of arrays and objects as you drill down:
```js
function a() {
var b = {
// comment
};
return b;
}
```
I'm going to test out the main ESLint repo with this branch now, but wanted to see if I could get some …

Fix: Fix behavior of ignoring comments within previous nodes (refs #256)

---

package.json
tools/generate-test-fixture.js

Because:
1. [`optimist`](https://www.npmjs.com/package/optimist) package was [deprecated](https://github.com/substack/node-optimist/commit/815c965cee7682ae2c6a80f8b306d20c81eb199a)  long ago.
2. It can be replaced with a simple, enough readable native method.
Otherwise, I recommend to use [minimist](https://www.npmjs.com/package/minimist) instead.

Build: replace optimist with a simple native method

---

CONTRIBUTING.md

Currently http://eslint.org/docs/developer-guide/contributing.html returns 404.

Docs: replace a dead link with the correct contributing guide URL

---

lib/token-translator.js
tests/lib/tokenize.js

Fixes #293.
Espree does not handle the previous `}` token at the first back quote of a template literal. As a result, the template literal is made from [ <code>\`</code>, `}`, `template`, <code>\`</code> ] sequence. The 2nd item `}` is the lost `}` token.
This PR makes espree handling the previous `}` token at the first back quote of a template literal.

Fix: `}` token followed by template had been lost (fixes #293)

---

package.json

See 
- https://github.com/ternjs/acorn/issues/496
- https://github.com/ternjs/acorn/issues/497

Build: Lock acorn to v4.0.4

---

.travis.yml
tests/fixtures/ecma-version/6/regexUFlag/regex-u-extended-escape.result.js
tests/fixtures/ecma-version/6/regexUFlag/regex-u-invalid-extended-escape.result.js
tests/fixtures/ecma-version/6/regexUFlag/regex-u-simple.result.js
tests/fixtures/ecma-version/6/regexYFlag/regexp-y-simple.result.js
tests/lib/conditional-regex-value.js
tests/lib/tester.js

There are a few issues with the tests causing them to fail with Node 6 and above:
* When parsing regular expression literals with the `y` and `u` flags, espree expected the `value` property of the resulting `Literal` node to `null`. However, since Node 6+ supports these flags, the `value` property was actually a regular expression with the corresponding flags. This commit updates the tests to conditionally expect a regex or `null` depending on whether the flags are supported in the current environment.
* For invalid regular expressions with the `u` flag, Acorn outputs a different error message depending on whether the current environment supports the `u` flag. This commit updates the tests to conditionally expect a particular error message depending on whether the current environment …

Chore: fix tests for Node 6+

---

espree.js
package.json
tests/fixtures/ecma-version/6/modules/export-default-parenthesized-class.result.js
tests/fixtures/ecma-version/6/modules/export-default-parenthesized-class.src.js
tests/fixtures/ecma-version/6/modules/export-default-parenthesized-function.result.js
tests/fixtures/ecma-version/6/modules/export-default-parenthesized-function.src.js
tests/fixtures/ecma-version/8/modules/export-default-async-expression.result.js

> ### Bug fixes
> Raise an error for duplicated lexical bindings.
> Fix spurious error when an assignement expression occurred after a spread expression.
> Accept regular expressions after `of` (in `for`/`of`), `yield` (in a generator), and braced arrow functions.
> Allow labels in front or `var` declarations, even in strict mode.
> ### Breaking changes
> Parse declarations following `export default` as declaration nodes, not expressions. This means that class and function declarations nodes can now have `null` as their `id`.

Upgrade: acorn to 5.0.1

---

espree.js
tests/lib/parse.js
tests/lib/tokenize.js

Previously, espree was adding `impliedStrict: false` to user-provided `ecmaFeatures` objects. This led to confusion and caused errors when using a frozen config. This commit updates the `tokenize` and `parse` functions to clone objects before mutating them.

Fix: don't mutate user-provided configs (fixes #329)

---

package.json

This upgrades our `eslint` devDependency to the latest version that we can support while still supporting Node < 4. Previously, we were using `2.0.0-beta1`.

Upgrade: eslint to 2.13.1

---

lib/ast-node-types.js

This adds `AwaitExpression` to `espree.Syntax`. It looks like this wasn't added when we started supporting async functions.

Fix: add AwaitExpression to espree.Syntax (fixes #331)

---

README.md

@kaicataldo how does this look for you?

Docs: Specify default values of options (fixes #325)

---

README.md
espree.js
lib/token-translator.js
tests/fixtures/ecma-version/9/malformed-template-literal-escape.result.js
tests/fixtures/ecma-version/9/malformed-template-literal-escape.src.js

~~(Builds on #347, look at that first)~~
This adds support for `ecmaVersion: 2018` (or `ecmaVersion: 9`). Currently, the only stage 4 proposal in ES2018 is the [template literal revision](https://github.com/tc39/proposal-template-literal-revision), which Acorn now supports in 5.1.0.

Update: add initial support for ES2018

---

espree.js
tests/fixtures/ecma-version/8/modules/async-object-method-keyword.result.js
tests/fixtures/ecma-version/8/modules/async-object-method-keyword.src.js

This ports the fix for https://github.com/ternjs/acorn/issues/584 to Espree's version of the overriden function.

Fix: Fix parsing of async keyword-named object methods (#352)

---

.npmrc

This PR adds `.npmrc` to not generate `package-lock.json` by npm. This is the same as `eslint/eslint` repo.

Chore: add .npmrc

---

espree.js

This PR includes #360.
This PR does a refactoring about rest/spread properties.
We can pretty simplify the code of rest/spread properties because Acorn extracted the code about properties into `parseProperty` (https://github.com/ternjs/acorn/commit/4747645d806b8ce5ab2e2fc136f1c17746b17640).

Chore: refactoring rest/spread properties

---

README.md

This PR removes the mentioning of the `blockBindings` option from the *Differences from Espree 2.x* section in the README as it is no longer supported and the opt-in apparently not necessary anymore.
> ~let and const declarations are no longer parsed by default. You must opt-in using ecmaFeatures.blockBindings.~

Fix: Remove blockBindings from docs (fixes #307, fixes #339)

---

espree.js
package.json
tests/fixtures/ecma-version/6/modules/invalid-await.result.js
tests/fixtures/ecma-version/8/modules/async-func.result.js
tests/fixtures/ecma-version/8/modules/await-identifier-math.result.js
tests/fixtures/ecma-version/8/modules/invalid-await-arrow-param-parens.result.js
tests/fixtures/ecma-version/8/modules/invalid-await-arrow-param.result.js
tests/fixtures/ecma-version/8/modules/invalid-await-destructured-param.result.js
tests/fixtures/ecma-version/8/modules/invalid-await-named-destructured-array-param.result.js
tests/fixtures/ecma-version/8/modules/invalid-await-named-destructured-param.result.js
tests/fixtures/ecma-version/8/modules/invalid-await-top-level.result.js
tests/fixtures/ecma-version/8/modules/invalid-plain-await.result.js
tests/fixtures/ecma-version/8/modules/plain-await.result.js

This PR fixes some test failures that acorn v5.3.0 introduced.
- It added a new argument to some methods we are overriding: `toAssignable` and `checkPropClash`. It didn't seem to trigger crashes but caused to overlook some syntax errors.
- It improved the error message around `async`/`await`.

Upgrade: acorn v5.3.0

---

.gitattributes

Keeping it simple for now. Please clone the branch locally and test.
Note that 17 tests will fail because `acorn@^5.2.1` pulls in 5.3.0, fixed by #365. I'll rebase once that gets merged.

Chore: Adding .gitattributes file

---

package.json
tests/fixtures/ecma-version/6/templateStrings/octal-literal.result.js

acorn 5.5.1 changed an error message (see acornjs/acorn#678). This PR fixes the tests to expect the new message.

Upgrade: acorn 5.5.1

---

package.json

This will ensure that when a prerelease is created from this repository, the release notes are pushed to GitHub.

Upgrade: eslint-release to v0.11.1

---

.eslintrc
.gitignore
.nycrc
Makefile.js
espree.js
lib/espree.js
package.json

This PR upgrades some dependencies:
- `acorn` to 6.0.2 ... This major version has changed the plugin system drastically.
- `acorn-jsx` to 5.0.0 to use new plugin system.
- `istanbul` to `nyc`, the official successor of `istanbul`, to measure coverage for ES2015 syntax (I encountered some conversion errors).
This PR moves the `acorn` plugin part to `./lib/espree.js` from `./espree.js`. (...and I deleted some unused logics.) New plugin system is class-based, so I use symbols to store private stuff in order to vaoid confliction with acorn's private stuff.
Probably this upgrade will fix https://github.com/eslint/eslint/issues/10623.
Fixes #390.

Upgrade: acorn 6, acorn-jsx 5, and istanbul

---

.eslintignore
.eslintrc
.eslintrc.js
Makefile.js
package.json
tests/lib/.eslintrc

Wanted to bring this more in line with how we have our linting set up in the main ESLint repo.

Chore: update linting config

---

lib/espree.js
tests/lib/ecma-version.js
tests/lib/parse.js

it will throw an error if any of the conditions is true:
+ ecmaVersion is invalid
+ sourceType is invalid
+ ecmaVersion < 6 & sourceType: "module"
is there some more conditions need to be covered?

Breaking: validate parser options (fixes #384)

---

lib/espree.js
tests/lib/tokenize.js

There is a logic in `TokenTranslator::onToken` about the latest curly brace
https://github.com/eslint/espree/blob/6ebc21947166399a0b4918d4a1beb9d610650336/lib/token-translator.js#L196-L204
But it executes only at first `eof` token (it seems strange that the first token is `eof`, but it comes from Acorn's init state)
I've added a call of `next` for the `TokenTranslator::onToken` to be executed with the last `eof` token
And I've noticed two failed tests, but they've already fixed at #416

Fix: tokenize the latest right curly brace (fixes #403)

---

lib/espree.js
tests/lib/ecma-version.js

Inspired by https://github.com/eslint/eslint/issues/12101. This PR enhances the error messaging when validating `ecmaVersion` to distinguish between when the the value provided is the incorrect data type versus when it's not a valid numeric value.
I labeled this an enhancement since it's not technically a bug fix, but please let me know if you disagree!

Update: improve error messaging when validating ecmaVersion

---

README.md

Updating the readme to document the new `ecmaVersion: 2020` option introduced in  https://github.com/eslint/espree/commit/f5e58cc5e9030793baca3426366b8d7286ef5b89.

Docs: update readme to mention ES2020

---

lib/espree.js
package.json

This PR fixes #393 and https://github.com/eslint/eslint/issues/11018.
Most of the diff in this PR are indentation. Please see with [`?w=1` option](./426/files?w=1).

Fix: misuse token types (fixes #393, refs eslint/eslint#11018)

---

espree.js
lib/espree.js
lib/options.js
tests/lib/supported-ecmaversions.js

Inspired by [this discussion](https://github.com/eslint/eslint/pull/12879#discussion_r376182196), this is a proposal to add `latestEcmaVersion()` & `supportedEcmaVersions()` to the public API.
Benefits:
1. We can query the latest `ecmaVersion` from the parser for rules (as is mentioned in the comment listed above).
1. The supported `ecmaVersion`s in our demo have gotten out of sync with ESLint core. This would allow us to calculate this programmatically and not have to manually update it.
1. This is a fairly minimal API that shouldn't require much maintenance. We will most likely adjust this code once a year.
Cons:
1. This increases the surface area of our API and will have to be maintained.
Open questions:
1. If we use this in core, are we expecting 3rd party parsers to also implement …

Update: add latestEcmaVersion & supportedEcmaVersions

---

package.json
tests/fixtures/ecma-features/jsx/embedded-tags.result.js
tests/fixtures/ecma-features/jsx/embedded-tags.src.js

`acorn-jsx` released v5.2.0, which includes the changes from [this PR](https://github.com/acornjs/acorn-jsx/pull/108). Since we have the same test in this repo, tests are failing in `master`. Updating the package.json and tests will ensure that tests pass again.
I've labeled this as an "Update" because I believe it should be treated as a semver-minor bug fix, since it is a bug fix that will lead to more errors.
More details can be found [here](https://github.com/acornjs/acorn-jsx/issues/106).

Update: update acorn-jsx and fix failing test

---

package.json

fixes "Regular Expression Denial of Service" vulnerability (fixes #435)

Upgrade: acorn to 7.1.1

---

tests/lib/options.js

added tests for `lib/options.js`

Chore: added tests for options normalize

---

Makefile.js
README.md
docs/README.md
docs/index.html
package.json

fixes #431
- Added docs for public apps.
- added their description 
- added parameters (if any)
- added example and output (as collapsible )
- Separate section for `options`
- Added script to sync the `README.md` from root to `docs/` directory.
- [`preview`](https://5ea045ab9ce8a400088866ca--espree.netlify.app/#/)

Docs: documenting public API (fixes #431)

---

.travis.yml
package.json

Now that Node v8 is no longer being supported (and we're dropping support in ESLint core), it seems prudent to also drop support in Espree.
Questions:
Have I missed anything?

Breaking: drop Node v8 support

---

Makefile.js
package.json

added a fixlint command and script in order to fix the autofixable linting issue

Chore: added fixlint in Makefile.js

---

LICENSE

Updated the LICENSE file with two changes:
1. Proper BSD 2-clause license formatting (according to GitHub -- helps with detecting the license of the project)
2. Updated the copyright to Open JS Foundation
This does not change the license type of the project, which remains BSD 2-clause, this is just some housekeeping.

Docs: Clean up LICENSE file

---

README.md

This adds a link to our security policy into the README (as required by Tidelift).

Docs: Add security policy

---

tests/lib/options.js
tests/lib/parse.js
tests/lib/tokenize.js

Adds a couple of tests to ensure that `ecmaVersion: 5` is the default. I'm not sure if we already had any explicit ones.

Chore: Add tests for ecmaVersion default value

---

package.json
tests/fixtures/ecma-features/jsx/yield-jsx-element.result.js
tests/fixtures/ecma-features/jsx/yield-jsx-element.src.js

Upgrades `acorn-jsx` from `5.2.0` to `5.3.1`.
* `5.3.0` adds acorn 8 to peer dependencies: https://github.com/acornjs/acorn-jsx/commit/2a24a4e6952c82923a9b618fcfccc261321e8804
* `5.3.1` fixes a bug with yielding unparenthesized jsx elements (https://github.com/acornjs/acorn-jsx/issues/82): https://github.com/acornjs/acorn-jsx/commit/642275fdb309144b54b3fbd9699639756ed9aad9

Upgrade: acorn-jsx@5.3.1

---

package.json

Upgrades `eslint-visitor-keys` from `1.3.0` to `2.0.0`.
The only change in `2.0.0` was dropping support for Node < 10: https://github.com/eslint/eslint-visitor-keys/commit/fb86ca315daafc84e23ed9005db40b0892b972a6
Espree already doesn't support Node < 10:
https://github.com/eslint/espree/blob/fef6f4a2803d959304c6961527044bd9da39ac92/package.json#L12-L14

Upgrade: eslint-visitor-keys@2.0.0

---

tests/lib/parse.js

Test that buffers and strings produce equal output to resolve uncovered line.

Chore: Add test for valid non-string input

---

Makefile.js
README.md
docs/README.md
package.json

Removes browserify script.
It doesn't look like we're publishing the bundle it creates, or using the script/bundle for anything, so it seems there is no point in maintaining the script.
Note: `npm run sync-docs` updated `docs/README.md` with some unrelated changes that were not synced before.

Build: remove browserify script

---

package.json
tests/lib/conditional-regex-value.js
tests/lib/ecma-version.js

This PR:
* Upgrades to `eslint-config-eslint@7.0.0`, and fixes new linting errors.
* Adds `eslint-plugin-jsdoc`.
* Bumps `eslint` and `eslint-plugin-node` to the latest versions.

Upgrade: eslint devDependencies

---

package.json
tests/lib/parse.js

fixes #470
changelog:
https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md#breaking-changes

Breaking: acorn to 8.1.0 (fixes #470)

---

.github/workflows/ci.yml

Switches the CI references from master to main. My understanding is that this will redirect automatically even without making this change, but better to be explicit.

Build: Update branch reference in CI

---

package.json
tests/lib/ecma-features.js
tests/lib/ecma-version.js
tests/lib/libraries.js

just replace leche.withData() => Array.prototype.forEach()

Chore: rm devdep leche (fixes #480)

---

.github/workflows/ci.yml

Removes `npm install --legacy-peer-deps` for Node 15 in `ci.yml`, since the issues we had with peer dependencies have been fixed.

Chore: remove --legacy-peer-deps for Node 15

---

lib/espree.js
tests/lib/parse.js

Syncing the range and loc with `start` and `end` for both `program` and `templateElement` nodes.

Breaking: syncing start/end with range (fixes #349)

---

lib/espree.js

Fix ranges/locations/start/end in one step, and use `TemplateElement.tail` instead of slicing the original input.

Chore: Refactor `TemplateElement` range fix

---

package.json

Upgrades `eslint-release` to the latest version, which supports the `main` branch.

Upgrade: eslint-release@3.1.2

---

README.md
lib/options.js
tests/lib/ecma-version.js
tests/lib/libraries.js
tests/lib/options.js
tests/lib/parse.js
tests/lib/tokenize.js

This is the implementation for #495, which:
1. Allows `ecmaVersion: "latest"` as a valid value. Internally, this is just normalized to `latestEcmaVersion`, as that was the simplest way to validate this value.
2. Sets the default `ecmaVersion` to `latestEcmaVersion`.

Breaking: Implement 'ecmaVersion: latest' (fixes #495)

---

README.md
lib/options.js
tests/lib/ecma-version.js
tests/lib/options.js
tests/lib/parse.js
tests/lib/tokenize.js

Per the 2021-06-17 TSC meeting, reverting so `ecmaVersion` is set to 5 if not present.

Update: reset default ecmaVersion to 5

---

espree.js
package.json

Updates espree to use the new eslint-visitor-keys v3.0.0 with ESM support.

Upgrade: eslint-visitor-keys@3.0.0

---

package.json
tests/fixtures/ecma-version/10/json-superset/valid-2028.result.js
tests/fixtures/ecma-version/10/json-superset/valid-2029.result.js
tests/fixtures/ecma-version/6/newTarget/invalid-new-target.result.js

This PR upgrades acorn to the latest v8.5.0, which includes a bug fix https://github.com/acornjs/acorn/commit/147b99e707d145b18971c0c755b645f9afdd7180 - `0x2028` and `0x2029` source code characters should increment line numbers in `loc` even if they're in string literals.
Our tests are now updated to reflect this change.

Fix: 0x2028 and 0x2029 in string literals should increment line number

---

tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-expr-new-target.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-expr-new-target.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-expr-this.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-expr-this.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-close.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-close.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-derived.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-derived.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-open.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-open.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-private.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-private.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-close.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-close.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-derived.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-derived.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-open.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-open.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-sequence.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-sequence.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-statement-list-optional.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-statement-list-optional.src.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-super-property.result.js
tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-super-property.src.js

acorn has been upgraded in ee1d3eca310cab1b1cf1563294434977d26358d4, this commit simply added some tests. The tests were copied from test262, refs: https://github.com/tc39/test262/commit/afe217b318df5f197e64b30a8b5a4b391c777359

Chore: add class static blocks tests

---

README.md
package.json

This PR aims to complete support for class static blocks, by:
* Updating `eslint-visitor-keys` dependency to make sure that `StaticBlock` is included in the `VisitorKeys` export. We're not using `espree.VisitorKeys` in eslint packages (we're using `eslint-visitor-keys` directly), but other dependent packages may be relying on this export.
* Updating documentation.
Tests that confirm that parsing of class static blocks already works were added in https://github.com/eslint/espree/pull/515.

feat: support class static blocks

---

package.json
tests/fixtures/ecma-version/13/private-in/invalid-missing-private.result.js
tests/fixtures/ecma-version/13/private-in/invalid-missing-private.src.js
tests/fixtures/ecma-version/13/private-in/invalid-without-class.result.js
tests/fixtures/ecma-version/13/private-in/invalid-without-class.src.js
tests/fixtures/ecma-version/13/private-in/valid-private-in.result.js
tests/fixtures/ecma-version/13/private-in/valid-private-in.src.js

This PR upgrades acorn to support ES2022 private-in.

feat: support for private-in syntax

---

README.md
lib/espree.js
lib/options.js
tests/lib/parse.js

Adds support for setting `sourceType: commonjs`. This causes the `globalReturn` flag to be set to `true` and changes `sourceType` on the `Program` node to be `"commonjs"`.
Related: https://github.com/eslint/eslint-scope/pull/81
Fixes #519

feat: Add sourceType:commonjs support

---

README.md

This PR documents that Espree supports private-in syntax (Ergonomic brand checks for Private Fields).

docs: add private-in syntax

---

README.md
lib/options.js
tests/lib/ecma-version.js

Fixes https://github.com/eslint/eslint/issues/15327

feat: add `allowReserved` for ES3

---

.github/workflows/ci.yml

Use node v16 for testing on macOS and windows.

ci: use node v16 for `macOS` and `windows` jobs

---

package.json
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-all-exported.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-all-exported.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-exported-with-escapes.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-exported-with-escapes.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-exported.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-exported.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-from-exported.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-from-exported.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-from-local-and-exported.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-from-local-and-exported.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-from-local.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-from-local.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-from-shorthand.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/export-from-shorthand.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/import-imported-with-escapes.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/import-imported-with-escapes.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/import-imported.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/import-imported.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/invalid-lone-surrogate-export-exported.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/invalid-lone-surrogate-export-exported.src.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/invalid-lone-surrogate-import-imported.result.js
tests/fixtures/ecma-version/13/modules/arbitrary-module-namespace-names/invalid-lone-surrogate-import-imported.src.js

Upgrades Acorn to support [Arbitrary module namespace names](https://github.com/tc39/ecma262/pull/2154).

feat: support arbitrary module namespace names

---

package.json

Updates `eslint-visitor-key` dependency to include https://github.com/eslint/eslint-visitor-keys/commit/5c532184e05440d3c883b3d7864f84eb1b11dc90

chore: upgrade eslint-visitor-keys@3.2.0

---

.github/workflows/ci.yml

Node v19.0.0 has been released.
https://nodejs.org/en/blog/release/v19.0.0/

ci: add node v19

---

.github/workflows/ci.yml

Use the [Node.js LTS version syntax](https://github.com/actions/setup-node#supported-version-syntax) so we don't have to manually update the node version in the future.

ci: use LTS node version in lint job

---

espree.js

This change adds a `name` export so that Espree can be properly serialized with the new serialization strategy in ESLint.
Refs https://github.com/eslint/eslint/pull/16944

feat: Add parser name

---

.github/workflows/release-please.yml

I believe our release-please workflow is missing an `npm install` step. Without that, the `npm publish` step would fail while running the `prepublishOnly` script due to missing dependencies (e.g., `rollup`)?

chore: add `npm install` step to release-please workflow

---

.github/workflows/add-to-triage.yml

Adds PRs to the triage project so we can manage issues and PRs in one place.

chore: Add PRs to triage project

---

.github/workflows/ci.yml
README.md
package.json

Refers https://github.com/eslint/eslint/issues/14827
This updates the names of the scripts in package.json to be consistent with the [new standard](https://eslint.org/docs/latest/contribute/package-json-conventions).
We may need to update the `release` related scripts on Jenkins before merging this PR.

chore: standardize npm script names

---

package.json
tests/fixtures/ecma-version/6/classes/class-one-method-super.result.js
tests/fixtures/ecma-version/6/forOf/for-of-with-function-initializer.result.js
tests/fixtures/ecma-version/6/modules/export-default-parenthesized-class.result.js
tests/fixtures/ecma-version/6/modules/export-default-parenthesized-function.result.js
tests/fixtures/ecma-version/6/modules/export-from-default.result.js
tests/fixtures/ecma-version/6/modules/export-from-named-as-default.result.js
tests/fixtures/ecma-version/6/modules/export-from-named-as-specifiers.result.js
tests/fixtures/ecma-version/6/modules/export-named-as-default.result.js
tests/fixtures/ecma-version/6/modules/export-named-as-specifier.result.js
tests/fixtures/ecma-version/6/modules/export-named-as-specifiers.result.js
tests/fixtures/ecma-version/6/modules/export-named-specifier.result.js
tests/fixtures/ecma-version/6/modules/export-named-specifiers-comma.result.js
tests/fixtures/ecma-version/6/modules/export-named-specifiers.result.js
tests/fixtures/ecma-version/6/modules/import-default-as.result.js
tests/fixtures/ecma-version/6/modules/import-named-as-specifier-keyword.result.js
tests/fixtures/ecma-version/6/modules/import-null-as-nil.result.js
tests/fixtures/ecma-version/6/modules/valid-await.result.js
tests/fixtures/ecma-version/6/regexUFlag/regex-u-extended-escape.result.js
tests/fixtures/ecma-version/6/regexUFlag/regex-u-simple.result.js
tests/fixtures/ecma-version/6/regexYFlag/regexp-y-simple.result.js
tests/fixtures/ecma-version/8/modules/async-object-method-keyword.result.js
tests/fixtures/ecma-version/8/not-strict/invalid-plain-await.result.js

the tests were updated:
* es6: 8f9f2fa67e492210aba90e6b96db4348e22ee0b3
* es8: 82afb5c2492bab066d0233ac2ec8bcdeefc3d00a

fix: upgrade acorn v8.11.3

---

package.json

Updates `eslint-visitor-keys` dependency to just-released v4.0.0.

chore: upgrade eslint-visitor-keys@4.0.0

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/change.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs.yml

chore: add issue templates

---

.github/workflows/update-readme.yml
tools/commit-readme.sh

Cron job to update sponsors in README.
We need to enable the `secrets.WORKFLOW_PUSH_BOT_TOKEN` secret for this repo. Can someone with access do it?

ci: auto update sponsors in README

---

packages/espree/package.json

chore: move to `npm-run-all2`

---

.github/ISSUE_TEMPLATE/config.yml
packages/eslint-scope/README.md
packages/eslint-scope/package.json
packages/espree/README.md
packages/espree/docs/README.md
packages/espree/docs/index.html
packages/espree/package.json

This PR updates several links to match the new monorepo name and structure.

fix: update links to `eslint/js` repo

---

packages/eslint-scope/README.md
packages/eslint-visitor-keys/README.md
packages/espree/README.md
packages/espree/docs/README.md

Updated links to the archived `eslint/eslint-visitor-keys` repo so they point to the `eslint/js` monorepo.

docs: update links to eslint-visitor-keys repo

---

packages/eslint-scope/lib/assert.js
packages/eslint-scope/lib/index.js
packages/eslint-scope/lib/referencer.js
packages/eslint-scope/lib/scope-manager.js
packages/eslint-scope/lib/scope.js

Removed `node:assert` as a dependency in `eslint-scope`, replacing it with a custom `assert` function.
Fixes #625 
Closes #626

fix: Remove node:assert dependency

---

packages/eslint-scope/rollup.config.js

As part of #633, the `assert` dependency was removed, so there’s no need to include it as an external dependency in the Rollup config.

chore: remove assert from rollup external array

---

packages/espree/README.md

In https://github.com/eslint/js/pull/641, support for Import Attributes and RegExp Modifiers was added to `packages/espree/docs/README.md`, but not also to `packages/espree/README.md`.
Updated `packages/espree/README.md`.
https://github.com/eslint/js/pull/639

docs: Support for Import Attributes and RegExp Modifiers

---

packages/eslint-scope/README.md
packages/eslint-scope/lib/index.js
packages/eslint-scope/lib/referencer.js
packages/eslint-scope/lib/scope-manager.js
packages/eslint-scope/lib/scope.js
packages/eslint-scope/tests/jsx.js
packages/eslint-scope/tests/util/espree.js

- Added a new `jsx` option to `analyze()`.
- Updated `Referencer` to track JSX references.
- Added tests to verify the behavior.
fixes #645
Please double-check that I'm covering enough scenarios in the tests. I'm not very familiar with JSX, so it's possible I missed some cases.

feat: Option to track JSX components as references

---

packages/eslint-visitor-keys/lib/visitor-keys.js

Change visitation order for `ExportSpecifier` to source code order.
Visit `local` before `exported`.
```js
export { local as exported };
```
Fixes #655.
I've opened this PR before anyone's had time to look at issue #655. I hope that's not considered rude. I hope it might be useful for checking if this change would break any rules (I assume it won't).

fix: order visitor keys for `ExportSpecifier` in source code order

---

packages/espree/package.json

Hello,
In this PR, I've replaced `npm-run-all2` with a native script.
This PR resolves #660.
While reducing devDependencies may not be critical in package development, I believe it's a good practice for the following reasons:
1. Performance - Faster install times and a smaller `node_modules`.
2. Maintenance - Fewer tools to update and manage.
3. Cleaner CI/CD - Leaner builds and more reliable pipelines.
4. Smaller footprint - Less clutter in the project, which is especially important for shared libraries.
fixes: #660

chore: replace `npm-run-all2` with a native script
