eslint/js

- tests/fixtures/ecma-features/modules/error-delete.result.js
- tests/fixtures/ecma-features/modules/error-delete.src.js
- tests/fixtures/ecma-features/modules/error-strict.result.js
- tests/fixtures/ecma-features/modules/error-strict.src.js
a few simple tests to ensure strict mode happens within modules
> Test: strict mode enforced in modules (refs #72)

- espree.js
- tests/fixtures/ecma-features/destructuring/params-multi-object.result.js
- tests/fixtures/ecma-features/destructuring/params-multi-object.src.js
- tests/fixtures/ecma-features/octalLiterals/strict-uppercase.result.js
- tests/fixtures/ecma-features/octalLiterals/strict-uppercase.src.js
- tests/lib/ecma-features.js
This basically runs all relevant `ecmaFeatures` tests for modules. I had to filter out a few (jsx and globalReturn) and also a few error case tests that behave differently inside of modules or with all flags enabled.
But...it all works!
> Update: Add tests for sourceType=module (refs #72)

- espree.js
- lib/comment-attachment.js
Related to https://github.com/jquery/esprima/issues/1068
> Update: Refactor out comment attachment logic

- README.md
> Docs: Clarify ecmaFeatures usage

- .travis.yml
I noticed travis.yml didn't have sudo false. It could be faster using their docker containers. http://docs.travis-ci.com/user/workers/container-based-infrastructure/
> Added sudo false to travis to build faster

- README.md
> Docs: fix `options.comment` typo

- package.json
- tests/fixtures/ecma-version/6/destructuring-and-spread/error-complex-destructured-spread-first.result.js
- tests/fixtures/ecma-version/6/destructuring-and-spread/invalid-not-final-array-empty.result.js
- tests/fixtures/ecma-version/6/destructuring-and-spread/not-final-array.result.js
- tests/fixtures/ecma-version/6/restParams/error-not-last.result.js
Fixes #270.
I fixed error messages of some tests.
I have a concern that `index` and `column` properties also have been changed.
> Upgdate acorn 3 1 0

- tools/create-test.js
Updated the `create-test` script to better support errors and really account for the acorn changes.
> Update: create-test script (fixes #291)

- espree.js
- tests/lib/ecma-version.js
This PR fixes: https://github.com/eslint/eslint/issues/7405
Let me know if theres anything else I need to do or if I missed something!
Thank you
cc @nzakas
> Fix:generic error for invalid ecmaVersion(fixes eslint#7405)

- espree.js
> Fix: remove workarounds for acorn < 4

- package.json
> Upgrade: acorn-jsx@5.0.2

- .gitignore
added 
```
yarn.lock
package-lock.json
```
to `.gitignore`
> Chore: added lockfiles to .gitignore

- .github/workflows/ci.yml
Adds Node 15.x to CI test matrix.
> Chore: Test on Node 15.x

- README.md
- docs/README.md
Updates the README with ESM instructions.
> Docs: Update README with ESM instructions (fixes #474)

- lib/espree.js
- tests/lib/parse.js
This addresses the comments left in #461 that hadn't yet been addressed.
> Chore: Add tests and comments for #349

- lib/espree.js
refs: https://github.com/eslint/espree/pull/490#discussion_r622740541
> Chore: fix incorrect comment

- package.json
- tests/lib/parse.js
seems it has been fixed in latest acorn
> Upgrade: acorn to 8.2.2 (fixes #472)

- .github/workflows/ci.yml
it's as the same as we have done in the eslint repo: eslint/eslint#14816
> Chore: use actions/setup-node@v2

- lib/espree.js
- lib/options.js
- tests/lib/ecma-version.js
Disallows reserved words in ES3 mode.
Refs eslint/eslint#15017
> Breaking: Disallow reserved words in ES3

- README.md
Updates the Build Status badge from Travis to GitHub Actions.
> docs: update Build Status badge

- tests/fixtures/ecma-version/13/class-static-blocks/LICENSE
Fix https://github.com/eslint/espree/issues/537
> chore: add LICENSE file

- package.json
Fix https://github.com/eslint/espree/issues/538
> chore: remove unused `devDependencies`

- README.md
Follow up https://github.com/eslint/espree/pull/556
> docs: update README for ES2023

- package.json
upgrades `eslint-visitor-keys@3.4.0`
> chore: upgrade eslint-visitor-keys@3.4.0

- .github/workflows/ci.yml
- package.json
refs: https://github.com/eslint/eslint/issues/17595
~~blocked by https://github.com/eslint/espree/pull/590~~
> feat!: Require Node.js ^18.18.0 || ^20.9.0 || >=21.1.0

- tools/create-test.js
- tools/update-tests.js
Same as https://github.com/eslint/espree/pull/608#discussion_r1639583293, just in the remaining two scripts that write files.
> chore: fix writing files in tools

- .github/PULL_REQUEST_TEMPLATE.md
> chore: Add pr template

- tools/update-readme.js
Removes an unnecessary IIFE in `tools/update-readme.js` to align this script with the same scripts in other repos.
Removed an IIFE in `tools/update-readme.js`.
> chore: Remove unnecessary IIFE in update-readme

- packages/espree/docs/README.md
Documents that Espree supports Import Attributes and RegExp Modifiers.
Updated `packages/espree/docs/README.md`.
https://github.com/eslint/js/pull/639
> docs: Support for Import Attributes and RegExp Modifiers

- .github/workflows/release-please.yml
Updated the `release-please` CI to also post to Bluesky.
> ci: Post to Bluesky on release

- .gitignore
- eslint.config.js
- package.json
Hello,
In this PR, I've updated ESLint config to use `defineConfig()` helper function.
I also added `*.code-workspace` to the `.gitignore` file.
This is follow-up to https://github.com/eslint/css/pull/145 and https://github.com/eslint/generator-eslint/pull/204.
> chore: update ESLint config to use `defineConfig`
